AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.5
  Exclude:
    - 'bin/**/*'
    - 'vendor/**/*'
Style/Documentation:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
Layout/LineLength:
  Max: 120
Style/Lambda:
  EnforcedStyle: literal
Style/GuardClause:
  Enabled: false
Metrics/MethodLength:
  Max: 20
Style/DoubleNegation:
  Enabled: false
Lint/UnusedMethodArgument:
  Exclude:
    - push/handler.rb
    - subscribe/handler.rb
